/**
 * agent-tcmedu-skills · 技能语料单一事实源 (Single Source of Truth)
 * ---------------------------------------------------------------
 * 本文件是全仓唯一的技能内容定义。skills/、catalog.json、
 * .well-known/skills/index.json 全部由 scripts/build-pack.mjs 从本文件生成。
 *
 * 修改技能内容 = 改本文件 + `npm run build`，禁止手改生成物。
 *
 * 字段约定见 docs/03-命名与编码规范.md。
 */

export const PACK = {
  name: 'agent-tcmedu-skills',
  version: '0.1.0',
  license: 'MIT',
  author: 'qhzytcm',
  upstreamPlatform: 'tcmP 中医药网络教育平台',
  platformBase: 'https://www.zyyywaccn.com.cn',
  generatedFrom: 'scripts/skills.spec.mjs',
};

/** 平台 API 契约（与 tcmP sage-api 对齐；详见 docs/02-与tcmP平台对接契约.md） */
export const PLATFORM_APIS = {
  '/health': '服务健康检查',
  '/sages': '医圣人格清单（张仲景 / 孙思邈）',
  '/agents/*': '六者 SOUL 智能体注册与查询（v3.0 新增，三端点）',
  '/consult/{sage_id}': '医圣咨询：主诉 + 症状 + 舌脉 → 辨证建议',
  '/teach/{sage_id}': '医圣授课：主题 + 学员层级 → 讲解',
  '/analyze-case/{sage_id}': '医圣病案分析',
  '/kg/query': '病证知识图谱检索',
  '/kg/detail/{dsu_id}': '病证单位（DSU）详情',
  '/kg/stats': '图谱规模统计',
  '/patients/symptom-check': '患者症状自查',
  '/patients/triage': '患者分诊导诊',
  '/patients/medication': '患者用药说明',
  '/pharmacists/review': '药者处方审核',
  '/pharmacists/interaction': '药者药物相互作用',
  '/pharmacists/substitute': '药者替代建议',
  '/pharmacists/inventory': '药者库存',
  '/pharmacists/trace': '药者饮片溯源',
  '/devices/maintenance': '械者设备维护',
  '/devices/imaging': '械者影像辅助',
  '/devices/procurement': '械者采购论证',
  '/devices/qc': '械者设备质控',
  '/devices/trace': '械者器械追溯',
  '/devices/emergency': '械者应急调度',
  '/regulators/quality': '规者质控管理',
  '/regulators/scheduling': '规者排班优化',
  '/regulators/utilization': '规者资源利用',
  '/regulators/dispatch': '规者应急调度',
  '/regulators/dashboard': '规者驾驶舱',
  '/legals/risk': '法者风险识别',
  '/legals/consent': '法者知情同意',
  '/legals/regulation': '法者法规查询',
  '/legals/cases': '法者案例库',
  '/legals/prevention': '法者纠纷预防',
  '/legals/insurance/coverage': '医保报销口径',
  '/legals/insurance/drug': '医保药品分类',
  '/legals/insurance/estimate': '费用估算',
  '/icd/*': 'ICD-11 编码桥接（内网 192.168.0.111:8080，v3.0 新增）',
  '/diag': '病证单元推理（v3.0 新增）',
  '/bianzheng': '辨证推理（v3.0 新增）',
  '/semantic-search': '语义检索（TF-IDF + FTS5 + RRF，内网零 token）',
  '/rag': 'RAG 精修问答',
};

/** 十二分类：与 tcmP 八域（D01–D08）+ 通用学习闭环 + 平台角色层 对齐 */
export const CATEGORIES = [
  { slug: 'tcm-foundation', zh: '中医基础与经典', en: 'TCM Foundation & Classics', domain: 'D01', desc: '中医基础理论、中医诊断学与四大经典（内经 / 伤寒 / 金匮 / 温病）的同步学习与经典研读能力。' },
  { slug: 'tcm-clinical', zh: '中医临床各科', en: 'TCM Clinical', domain: 'D01', desc: '中医内科、妇科、儿科及病案辨证实训：把临床课程转成可执行的辨证论治训练闭环。' },
  { slug: 'tcm-materia', zh: '中药与方剂', en: 'Materia Medica & Formulas', domain: 'D02', desc: '中药学、方剂学、炮制鉴定与饮片溯源：药性功效、配伍禁忌、方证对应的记忆与应用。' },
  { slug: 'tcm-acupuncture', zh: '针灸与推拿', en: 'Acupuncture & Tuina', domain: 'D03,D04', desc: '经络腧穴、刺法灸法、推拿手法：定位、主治、操作规范与临床配穴取穴训练。' },
  { slug: 'tcm-orthopedics', zh: '骨伤与五官口腔', en: 'Orthopedics, ENT & Stomatology', domain: 'D05,D06', desc: '中医骨伤科与五官口腔科：正骨理筋手法、创伤急救、眼科 / 耳鼻喉 / 口腔辨证。' },
  { slug: 'tcm-intelligence', zh: '中医智能', en: 'TCM Intelligence', domain: 'D07', desc: '中医智能学院：病证单位检索（RAG）、知识图谱查询、ICD-11 编码桥接、六者 SOUL 智能体锻造与中医 AI 课程实验。' },
  { slug: 'tcm-management', zh: '中医管理', en: 'TCM Management', domain: 'D08', desc: '中医管理学院的实务能力：医疗质控、排班调度、医保报销口径与医事法规。' },
  { slug: 'tcm-learning-core', zh: '学习核心', en: 'Learning Core', domain: '-', desc: '通用学习闭环：学习计划、错题复盘、拍照答疑、预习复盘与学情报告。' },
  { slug: 'tcm-exam-prep', zh: '考试备考', en: 'Exam Prep', domain: '-', desc: '中医执业医师资格考试、考研中医综合、住院医师规范化培训的备考闭环。' },
  { slug: 'tcm-role-agents', zh: '六者角色', en: 'Six-Role Agents', domain: '平台', desc: '医·患·药·械·规·法 六者角色技能：与 tcmP 平台 sage-api 六组端点一一绑定。' },
  { slug: 'tcm-sage-growth', zh: '医圣成长', en: 'Sage Growth', domain: '平台', desc: '医圣人格带教与成长路径：张仲景 / 孙思邈人格授课、病证数门槛与职称映射考核。' },
  { slug: 'tcm-teacher-tools', zh: '教研工具', en: 'Teacher Tools', domain: '-', desc: '面向教师与师承带教者：中医备课、教案设计、命题组卷与课堂学情分析。' },
];

/**
 * 技能种子集。
 * 生成器会为本处未显式给出的字段补齐分类级默认值。
 */
export const SKILLS = [
  // ════════ tcm-foundation：中医基础与经典 ════════
  {
    slug: 'tcm-basic-theory', title: '中医基础理论 Skill', category: 'tcm-foundation',
    summary: '把阴阳五行、藏象、气血津液、经络、病因病机转成可自检的概念网络学习任务。',
    problem: '中医基础理论概念密集且相互定义，学习者容易「背得下名词、串不起关系」。本 Skill 把 S01 教材的章节骨架转成概念网络，让学习者每完成一次学习都能回答「这个概念和谁有关、靠什么证据成立」。',
    bestFor: ['本科U2–U3 按 CM-01 教材同步学习', '跨专业转中医者的补基础', '考研中医综合的中基一轮复习'],
    notFor: ['代替临床课程与临床实习', '在没有教材版本与章节信息时的凭空讲授'],
    inputs: ['教材版本与章节（默认 CM-01 中医基础理论）', '当前学段与基础水平', '每天可投入时间'],
    workflow: ['锚定章节与核心概念清单', '构建概念关系网（属种 / 因果 / 对立制约）', '每概念给出「定义—原文依据—反例」三件套', '生成 5–8 道概念辨析题并当堂判分', '输出本次掌握度与下一步建议'],
    outputs: ['概念网络图（Markdown 表格）', '辨析题与判分', '掌握度与下一步'],
    textbookCodes: ['CM-01'], subjects: ['中医基础理论'], abilities: ['概念网络', '知识记忆'],
    scenarios: ['课前预习', '同步巩固', '单元复习'], stages: ['本科'], tags: ['基础', '藏象', '阴阳五行', '经络'],
  },
  {
    slug: 'tcm-diagnostics', title: '中医诊断学 Skill', category: 'tcm-foundation',
    summary: '把望闻问切四诊信息规范成可复用的采集表单，并训练「四诊合参→辨证要素」的推理链。',
    problem: '诊断学的难点不在记症状，而在把杂乱的四诊信息收敛成证候要素。本 Skill 强制结构化采集，再把信息逐层收敛，避免「一症一证」的跳跃式结论。',
    bestFor: ['本科U3–U4 按 CM-02 教材同步学习', '病案讨论前的四诊信息整理', '执业医师实践技能的四诊训练'],
    notFor: ['替代真实患者的面诊', '在缺舌脉信息时给出确诊式结论'],
    inputs: ['主诉与现病史', '望闻问切四诊信息（舌象 / 脉象可留空）', '既往史与用药史'],
    workflow: ['按四诊表单结构化采集', '逐项标注异常与阳性体征', '归纳病位（脏腑 / 经络）与病性（寒热虚实）', '形成证候要素清单并给出并列候选项', '提示需要补充的关键信息'],
    outputs: ['四诊结构化记录', '病位病性归纳表', '证候要素候选与补充信息提示'],
    textbookCodes: ['CM-02'], subjects: ['中医诊断学'], abilities: ['四诊合参', '辨证要素'],
    scenarios: ['同步巩固', '病案讨论'], stages: ['本科'], tags: ['四诊', '舌诊', '脉诊', '辨证要素'],
  },
  {
    slug: 'tcm-neijing', title: '内经选读 Skill', category: 'tcm-foundation',
    summary: '《黄帝内经》原文—注释—译文三层对照研读，并把经文落到现代生理与临床场景。',
    problem: '内经学习常卡在「文言读不懂」与「读懂了不知道有什么用」两端。本 Skill 用三层对照解决前者，用「经文—现代映射—临床场景」解决后者。',
    bestFor: ['本科U4–U5 按 CM-09 教材研读', '素问 / 灵枢重点篇目的精读', '研究生追溯中医理论源头'],
    notFor: ['把内经当纯古文翻译练习', '脱离篇目主旨的断章取义'],
    inputs: ['篇目名称（如《素问·阴阳应象大论》）', '原文段落或教材页码', '研读深度（本科 / 研究生）'],
    workflow: ['定位篇目主旨与该篇在全书的位置', '原文逐句分层：字词—句读—义理', '给出注释与白话译文', '做「经文→现代生理/病理」映射', '提炼可迁移的临床原则并给出后世医家印证'],
    outputs: ['三层对照研读卡', '经文—现代映射表', '临床原则提炼'],
    textbookCodes: ['CM-09'], subjects: ['内经选读'], abilities: ['经典研读', '医古文'],
    scenarios: ['经典研读', '单元复习'], stages: ['本科', '硕士'], tags: ['内经', '素问', '灵枢', '原文'],
  },
  {
    slug: 'tcm-shanghan', title: '伤寒论讲义 Skill', category: 'tcm-foundation',
    summary: '按六经辨证把《伤寒论》条文整理成「方证—脉证—治法—禁忌」四栏可检索卡片。',
    problem: '伤寒论 398 条条文分散且互文性强，学习者记不住「哪条对哪方、哪方治哪证」。本 Skill 用四栏卡片把条文结构化，并建立方证索引。',
    bestFor: ['本科U5–U6 按 CM-10 教材学习', '经方方证对应的专项记忆', '临床用经方前的方证核对'],
    notFor: ['替代原书通读', '跳过条文依据直接给方'],
    inputs: ['条文号或方剂名（如「桂枝汤」「第 12 条」）', '学习目标（记方 / 辨脉 / 类方比较）', '当前学段'],
    workflow: ['定位条文与所属六经病篇', '拆解为方证 / 脉证 / 治法 / 禁忌四栏', '与同类方做鉴别（如桂枝汤类方）', '给出后世注家要点（成无己 / 柯琴等）', '生成方证对应默写与判分'],
    outputs: ['条文四栏卡', '类方鉴别表', '方证默写与判分'],
    textbookCodes: ['CM-10'], subjects: ['伤寒论讲义'], abilities: ['六经辨证', '经方方证'],
    scenarios: ['经典研读', '考前背诵'], stages: ['本科', '硕士'], tags: ['伤寒论', '六经', '经方', '方证对应'],
  },
  {
    slug: 'tcm-wenbing', title: '温病学 Skill', category: 'tcm-foundation',
    summary: '卫气营血与三焦两条辨证主线并行，配合四大家学说与温病方剂的情境化应用。',
    problem: '温病学的辨证框架（卫气营血 / 三焦）与伤寒的六经框架容易混淆，学习者常在两条线之间来回漂移。本 Skill 强制选定主线并在另一条线上做交叉校验。',
    bestFor: ['本科U6 按 CM-12 教材学习', '湿热类温病的辨证训练', '伤寒—温病辨证框架对比复习'],
    notFor: ['替代《温热论》《温病条辨》原典研读', '在病因不明时套用温病方'],
    inputs: ['病例或条文（症状 + 病程 + 舌脉）', '希望使用的辨证主线（卫气营血 / 三焦）', '学习目标'],
    workflow: ['判定新感 / 伏邪与病邪性质（温热 / 湿热）', '沿主线定位病位层次', '在另一条主线上交叉校验', '给出治法与代表方（银翘散 / 清营汤 / 三仁汤等）', '提示传变风险与观察要点'],
    outputs: ['双主线辨证定位', '治法方药', '传变与观察要点'],
    textbookCodes: ['CM-12'], subjects: ['温病学'], abilities: ['卫气营血辨证', '三焦辨证'],
    scenarios: ['同步巩固', '病案讨论'], stages: ['本科'], tags: ['温病', '卫气营血', '三焦', '湿热'],
  },

  // ════════ tcm-clinical：中医临床各科 ════════
  {
    slug: 'tcm-internal-medicine', title: '中医内科学 Skill', category: 'tcm-clinical',
    summary: '按「病—证—法—方—药」五级落点，把内科各病种的辨证分型训练成可判分的诊疗路径。',
    problem: '内科病种的辨证分型表背下来容易，但遇到真实主诉就选不准证型。本 Skill 用五级落点强制每一步都有依据，暴露「跳步选方」的错误。',
    bestFor: ['本科U6–U7 按 CM-13/CM-14 教材学习', '规培病案的辨证论治演练', '执业医师病例题训练'],
    notFor: ['替代临床带教与真实接诊', '对急危重症给出门诊式处理建议'],
    inputs: ['主诉与现病史', '四诊信息（舌脉）', '既往治疗与疗效', '病种（可留空由系统推断）'],
    workflow: ['定位病种与诊断依据', '列出该病常见证型并逐项比对', '确定证型并给出鉴别理由（为何不是相邻证型）', '沿证型给出治法—主方—加减', '标注疗效判定节点与复诊时机'],
    outputs: ['病—证—法—方—药五级路径表', '相邻证型鉴别', '疗效判定与复诊节点'],
    textbookCodes: ['CM-13', 'CM-14'], subjects: ['中医内科学'], abilities: ['辨证分型', '治法方药'],
    scenarios: ['病案讨论', '规培演练'], stages: ['本科', '规培'], roles: ['healer'], tags: ['内科', '辨证分型', '治法方药'],
  },
  {
    slug: 'tcm-gynecology', title: '中医妇科学 Skill', category: 'tcm-clinical',
    summary: '以「经带胎产」四期为轴，把妇科病种的周期疗法与调周法落到具体方药与时机。',
    problem: '妇科用药强调「因时制宜」，同一病种在不同周期用方不同。本 Skill 把时间轴显式化，避免不分周期一律用同一方。',
    bestFor: ['本科U7 按 CM-16 教材学习', '月经病周期疗法的专项训练', '妇科病案讨论'],
    notFor: ['替代妇科专科检查与影像', '妊娠期用药的自主建议（须强调就医）'],
    inputs: ['主诉（经 / 带 / 胎 / 产范畴）', '月经史（周期 / 经量 / 色泽 / 伴随症状）', '当前所处周期阶段', '舌脉'],
    workflow: ['归入经带胎产四期范畴', '明确病种与主要证型', '沿周期阶段给出分阶段用方', '标注妊娠禁忌与用药安全提示', '给出调护与复诊节点'],
    outputs: ['病种—证型—周期用方表', '妊娠禁忌提示', '调护与复诊节点'],
    textbookCodes: ['CM-16'], subjects: ['中医妇科学'], abilities: ['周期疗法', '调周法'],
    scenarios: ['病案讨论', '同步巩固'], stages: ['本科', '规培'], roles: ['healer'], tags: ['妇科', '月经病', '周期疗法', '妊娠禁忌'],
  },
  {
    slug: 'tcm-pediatrics', title: '中医儿科学 Skill', category: 'tcm-clinical',
    summary: '按小儿生理特点调整问诊重心与用药剂量，把儿科病种转成家长可执行的照护任务。',
    problem: '儿科问诊依赖家长转述、用药剂量随年龄体重变化，通用内科思路直接套用会出错。本 Skill 内置儿科问诊模板与剂量阶梯。',
    bestFor: ['本科U8 按 CM-17 教材学习', '儿科门诊前的信息准备', '家长照护要点讲解'],
    notFor: ['替代儿科急诊判断', '对高热惊厥等急症给居家处理建议'],
    inputs: ['患儿年龄 / 体重', '家长主诉与现病史', '喂养与二便情况', '舌象（可留空）'],
    workflow: ['按儿科问诊模板补全信息', '归入儿科病种与证型', '按年龄体重给出剂量区间', '输出家长可执行的照护与观察要点', '标注需立即就医的红旗症状'],
    outputs: ['儿科结构化问诊记录', '证型与剂量区间', '照护要点与就医红旗'],
    textbookCodes: ['CM-17'], subjects: ['中医儿科学'], abilities: ['儿科问诊', '剂量阶梯'],
    scenarios: ['病案讨论', '家长沟通'], stages: ['本科', '规培'], roles: ['healer', 'patient'], tags: ['儿科', '剂量', '家长沟通', '红旗症状'],
  },
  {
    slug: 'tcm-case-dialectics', title: '病案辨证实训 Skill', category: 'tcm-clinical',
    summary: '拉取平台病证单位（DSU）真实病案，做「以病索证 / 以证溯病」的双向辨证对抗训练。',
    problem: '课堂病案经过简化，真实病案信息冗余且干扰项多。本 Skill 直接调用 tcmP 图谱的病证单位，做带评分标准的双向检索训练。',
    bestFor: ['临床课程后的综合演练', '规培阶段的高频病证覆盖', '中医智能方向的数据理解实训'],
    notFor: ['替代真实接诊', '在离线环境下使用（需平台可达）'],
    inputs: ['训练方向（以病索证 / 以证溯病）', '病种或证型关键词', '难度与题量'],
    workflow: ['调用 /kg/query 检索病证单位', '隐藏标准答案后给出病案描述', '学习者提交辨证结论', '对照 DSU 标准答案逐项评分', '生成错题并建议下一轮病证范围'],
    outputs: ['病案题面', '逐项评分表', '错题清单与下一轮范围'],
    apis: ['/kg/query', '/kg/detail/{dsu_id}', '/diag', '/bianzheng'],
    subjects: ['中医临床综合'], abilities: ['双向辨证', '病证检索'],
    scenarios: ['综合演练', '规培演练'], stages: ['本科', '规培'], standaloneSupport: 'needs_platform',
    tags: ['病案', 'DSU', '以病索证', '以证溯病'],
  },

  // ════════ tcm-materia：中药与方剂 ════════
  {
    slug: 'tcm-materia-medica', title: '中药学 Skill', category: 'tcm-materia',
    summary: '按「性味归经—功效—主治—用法用量—使用注意」五要素记忆中药，并做同类药横向比较。',
    problem: '中药数量多且功效高度相似，单味背记极易混淆。本 Skill 强制五要素结构 + 同类药横向对比表，把「记住」变成「分得清」。',
    bestFor: ['本科二年级按 MM-01 教材学习', '同类药（如清热解毒药群）横向辨析', '执业医师中药部分复习'],
    notFor: ['替代《中国药典》的法定标准', '给出个体化处方（须医师）'],
    inputs: ['中药名或药类（如「解表药」）', '学习目标（记功效 / 辨同类 / 记剂量）', '临床场景（可选）'],
    workflow: ['给出五要素结构化卡片', '列出同类药并做横向对比表', '标注易混淆点与鉴别口诀', '提示用法用量与使用注意（含妊娠禁忌）', '生成辨析题并判分'],
    outputs: ['五要素药卡', '同类药对比表', '辨析题与判分'],
    textbookCodes: ['MM-01'], subjects: ['中药学'], abilities: ['药性功效', '同类药辨析'],
    scenarios: ['同步巩固', '考前背诵'], stages: ['本科'], tags: ['中药', '性味归经', '功效', '使用注意'],
  },
  {
    slug: 'tcm-formulas', title: '方剂学 Skill', category: 'tcm-materia',
    summary: '从君臣佐使拆方义，把「方—证—法」绑定，并训练加减变化对功效的迁移。',
    problem: '背方歌能记住组成，但说不清「为什么这么配」。本 Skill 强制拆君臣佐使并做加减推演，把方剂学成可推理的结构。',
    bestFor: ['本科二年级按 MM-02 教材学习', '类方（如四君子汤类方）比较', '临床用方前的方义复核'],
    notFor: ['替代原方剂量与煎服法的权威依据', '在无证型依据时推荐成方'],
    inputs: ['方名或方类', '学习目标（拆方义 / 类方比较 / 加减推演）', '待匹配的证型（可选）'],
    workflow: ['列出组成、剂量与煎服法', '拆解君臣佐使与配伍意义', '绑定「方—证—法」三角', '做类方比较或加减推演（加一味 / 减一味对功效的影响）', '生成方证匹配题并判分'],
    outputs: ['方义拆解表', '方—证—法绑定', '类方比较 / 加减推演'],
    textbookCodes: ['MM-02'], subjects: ['方剂学'], abilities: ['方义配伍', '类方比较'],
    scenarios: ['同步巩固', '考前背诵'], stages: ['本科'], tags: ['方剂', '君臣佐使', '类方', '方证对应'],
  },
  {
    slug: 'tcm-herb-processing', title: '中药炮制与鉴定 Skill', category: 'tcm-materia',
    summary: '讲清「炮制减毒增效」的原理，并接入平台饮片溯源做过关式鉴定训练。',
    problem: '炮制前后的药性与毒性与临床安全直接相关，但教材多以记忆表呈现。本 Skill 用「原理—变化—临床后果」串起来，并接溯源接口做实操感。',
    bestFor: ['中药学与炮制方向的本科课程', '药房 / 药企新员工培训', '饮片验收的性状鉴别训练'],
    notFor: ['替代药检机构出具的检验报告', '给出自制饮片的非法操作规程'],
    inputs: ['药材名与待鉴定饮片描述（性状 / 颜色 / 气味）', '炮制方法（清炒 / 酒炙 / 醋炙等）', '训练目标（原理 / 鉴别 / 溯源）'],
    workflow: ['说明该炮制法的目的与原理', '对比炮制前后的成分与药性变化', '给出临床后果（减毒 / 增效 / 改变归经）', '调用 /pharmacists/trace 走一遍溯源链路', '生成性状鉴别过关题并判分'],
    outputs: ['炮制原理卡', '炮制前后对比', '溯源实训与鉴别判分'],
    apis: ['/pharmacists/trace', '/pharmacists/inventory'],
    textbookCodes: ['MM-03'], subjects: ['中药炮制学', '中药鉴定学'], abilities: ['炮制原理', '性状鉴别'],
    scenarios: ['实操训练', '企业培训'], stages: ['本科', '继续教育'], roles: ['pharmacist'], tags: ['炮制', '鉴定', '饮片溯源', '减毒增效'],
  },

  // ════════ tcm-acupuncture：针灸与推拿 ════════
  {
    slug: 'tcm-meridians-acupoints', title: '经络腧穴学 Skill', category: 'tcm-acupuncture',
    summary: '按「循行—定位—主治—配伍—禁忌」学习经络腧穴，并用体表标志法做定位自测。',
    problem: '腧穴定位差之毫厘谬以千里，纯文字描述难以自检。本 Skill 强制用体表标志 + 骨度分寸描述定位，并生成可自测的定位题。',
    bestFor: ['针灸推拿专业本科按 AT-01 教材学习', '执业医师针灸部分的定位复习', '临床配穴前的穴位复核'],
    notFor: ['替代人体解剖实训标本操作', '对危险穴位给出无防护的自行操作指导'],
    inputs: ['经脉名或腧穴名', '训练目标（循行 / 定位 / 主治 / 配穴）', '是否包含危险穴位提示'],
    workflow: ['给出经脉循行路线与交接', '按体表标志 + 骨度分寸描述腧穴定位', '列出主治与常用配伍', '标注针刺深度与危险穴位提示', '生成定位自测题并判分'],
    outputs: ['经脉循行卡', '腧穴定位与主治表', '配穴方案与安全提示', '定位自测判分'],
    textbookCodes: ['AT-01'], subjects: ['经络腧穴学'], abilities: ['腧穴定位', '配穴'],
    scenarios: ['同步巩固', '考前背诵'], stages: ['本科'], roles: ['healer'], tags: ['经络', '腧穴', '骨度分寸', '危险穴位'],
  },
  {
    slug: 'tcm-acupuncture-technique', title: '刺法灸法学 Skill', category: 'tcm-acupuncture',
    summary: '把毫针刺法、灸法、拔罐与电针的操作规范拆成可检查的步骤序列与安全边界。',
    problem: '刺灸操作是手法性的，书面学习容易跳过关键步骤（如消毒、得气判断）。本 Skill 把操作拆成可勾选的步骤序列并强制安全边界。',
    bestFor: ['针灸推拿专业本科按 AT-02 教材学习', '针灸科实习生操作前复核', '不良反应处置复习'],
    notFor: ['替代真人实操带教', '对无资质者给出侵入性操作指导'],
    inputs: ['术式（毫针刺法 / 灸法 / 拔罐 / 电针）', '训练阶段（初学 / 实习）', '是否存在禁忌情形'],
    workflow: ['列出术前准备与消毒步骤清单', '逐步说明进针、得气、行针、留针、出针', '标注禁忌部位与禁忌情形', '给出晕针 / 滞针 / 血肿的识别与处置', '生成步骤排序题与安全判断题'],
    outputs: ['术式操作步骤清单', '禁忌与不良反应处置表', '步骤排序与安全判分'],
    textbookCodes: ['AT-02'], subjects: ['刺法灸法学'], abilities: ['操作规范', '安全边界'],
    scenarios: ['实操训练', '实习复核'], stages: ['本科', '规培'], roles: ['healer'], tags: ['刺法', '灸法', '得气', '晕针处置'],
  },
  {
    slug: 'tcm-tuina', title: '推拿手法学 Skill', category: 'tcm-acupuncture',
    summary: '按「力度—频率—着力部位—操作要领」解析推拿手法，并给出可自练的分解动作。',
    problem: '推拿手法的评价依赖触感，自学难以判断是否达标。本 Skill 把手法的量化特征（力度、频率、幅度）显式化，并给出可自练的分级动作。',
    bestFor: ['推拿专业本科按 TU-01 教材学习', '家庭保健推拿的规范入门', '临床推拿前的手法选择'],
    notFor: ['替代专业手法带教的触感纠正', '对骨折、肿瘤等禁忌症给出推拿建议'],
    inputs: ['手法名（㨰 / 揉 / 推 / 拿 / 按 / 摩等）', '作用部位与治疗目的', '训练阶段'],
    workflow: ['说明手法的动作结构与发力方式', '给出力度、频率、幅度等量化特征', '列出操作要领与常见错误', '设计分级自练方案（镜子 / 米袋练习）', '标注禁忌症与终止指征'],
    outputs: ['手法量化卡', '常见错误对照', '分级自练方案与禁忌'],
    textbookCodes: ['TU-01'], subjects: ['推拿手法学'], abilities: ['手法操作', '量化参数'],
    scenarios: ['实操训练', '家庭保健'], stages: ['本科', '继续教育'], roles: ['healer', 'patient'], tags: ['推拿', '手法', '量化特征', '禁忌症'],
  },

  // ════════ tcm-orthopedics：骨伤与五官口腔 ════════
  {
    slug: 'tcm-orthopedics-trauma', title: '中医骨伤科学 Skill', category: 'tcm-orthopedics',
    summary: '把正骨理筋手法的适应证、复位标准与固定康复方案串成完整的骨伤处理链。',
    problem: '骨伤科易出现「手法选择随意、复位标准模糊」的问题。本 Skill 强制先给适应证与禁忌，再谈手法，最后落固定与康复。',
    bestFor: ['骨伤专业本科与研究生课程', '正骨手法适应证判断训练', '创伤急救流程复习'],
    notFor: ['替代影像学检查与手术评估', '对开放骨折、血管神经损伤给出非手术建议'],
    inputs: ['损伤部位与机制', '症状体征与影像描述（可留空）', '训练目标（手法 / 复位标准 / 康复）'],
    workflow: ['判定损伤类型与是否需手术转诊', '列出手法适应证与禁忌证', '说明手法操作与复位标准（X 线评估）', '给出固定方式与固定时长', '输出分阶段康复方案与复诊节点'],
    outputs: ['损伤判定与转诊提示', '手法适应证与复位标准', '固定与分阶段康复方案'],
    textbookCodes: ['OR-01'], subjects: ['中医骨伤科学'], abilities: ['正骨理筋', '固定康复'],
    scenarios: ['病案讨论', '实操训练'], stages: ['本科', '硕士'], roles: ['healer'], tags: ['骨伤', '正骨', '复位标准', '康复'],
  },
  {
    slug: 'tcm-ent-stomatology', title: '中医五官口腔科学 Skill', category: 'tcm-orthopedics',
    summary: '按「局部辨证 + 脏腑经络关联」处理眼、耳鼻喉、口腔疾病，避免只见局部不见整体。',
    problem: '五官科疾病的局部症状突出，容易脱离整体辨证而只做局部处理。本 Skill 强制局部与脏腑经络双向对照。',
    bestFor: ['五官口腔专业本科按 ENT-01 教材学习', '口疮、耳鸣、鼻渊等常见病的辨证训练', '局部用药与内服方的配合'],
    notFor: ['替代专科器械检查', '对视功能 / 听力急性下降等急症给出居家处置'],
    inputs: ['局部症状描述（部位 / 性质 / 病程）', '全身伴随症状与舌脉', '既往病史'],
    workflow: ['按局部辨证要点归纳主症', '关联相应脏腑经络（肝胆 / 脾胃 / 肾 / 肺）', '给出证型与内服治法方药', '给出局部外治或含漱、滴耳等方案', '标注需转诊的急症信号'],
    outputs: ['局部辨证表', '脏腑经络关联', '内外合治方案与转诊信号'],
    textbookCodes: ['ENT-01'], subjects: ['中医眼科学', '中医耳鼻喉科学', '中医口腔科学'], abilities: ['局部辨证', '内外合治'],
    scenarios: ['病案讨论', '同步巩固'], stages: ['本科', '规培'], roles: ['healer'], tags: ['五官', '口腔', '局部辨证', '内外合治'],
  },

  // ════════ tcm-intelligence：中医智能 ════════
  {
    slug: 'tcm-dsu-retrieval', title: '病证单位检索 Skill（RAG）', category: 'tcm-intelligence',
    summary: '用平台的病证单元引擎做检索增强问答：TF-IDF + FTS5 + RRF 融合，内网零 token。',
    problem: '大模型直接答中医问题会编造方剂与剂量。本 Skill 强制「先检索后生成」，所有结论必须落到检索到的病证单位上。',
    bestFor: ['中文医学文献 / 教材的问答检索', '构建中医 RAG 应用的工程学习', '离线低成本场景的知识问答'],
    notFor: ['替代临床决策', '在平台不可达时的离线使用'],
    inputs: ['自然语言问题或病证关键词', '返回条数 Top-K', '是否需要出处引用'],
    workflow: ['调用 /semantic-search 做语义检索', '对候选做 RRF 融合排序', '取 Top-K 病证单位原文', '调用 /rag 做精修问答与溯源', '输出答案 + 出处编号，无出处不输出'],
    outputs: ['检索候选列表', '融合排序结果', '带出处的精修答案'],
    apis: ['/semantic-search', '/rag', '/diag', '/bianzheng', '/kg/query'],
    subjects: ['中医智能', '信息检索'], abilities: ['检索增强生成', '出处溯源'],
    scenarios: ['科研检索', '应用开发'], stages: ['本科', '硕士', '博士'], standaloneSupport: 'needs_platform',
    tags: ['RAG', 'TF-IDF', 'FTS5', 'RRF', '病证单元'],
  },
  {
    slug: 'tcm-kg-query', title: '病证知识图谱查询 Skill', category: 'tcm-intelligence',
    summary: '查询病证知识图谱的节点与关系，支持以病索证、以证溯病双向遍历与规模统计。',
    problem: '图谱数据在平台里，学习者看不到结构，也难以验证「教材知识如何进入图谱」。本 Skill 把图谱查询变成可练习、可讲解的任务。',
    bestFor: ['中医智能方向的数据结构学习', '教材知识点与图谱节点的对照核查', '图谱质量抽查'],
    notFor: ['替代图谱构建工程本身', '在无权限时读取受限节点'],
    inputs: ['查询词（病名 / 证型 / 方剂 / 症状）', '查询类型（检索 / 详情 / 统计）', 'DSU 编号（可选）'],
    workflow: ['调用 /kg/query 做检索并展示命中节点', '按需调用 /kg/detail/{dsu_id} 取详情', '展示节点间关系（病—证—方—药）', '调用 /kg/stats 说明图谱规模', '输出教材知识点到图谱节点的映射表'],
    outputs: ['命中节点列表', '节点关系图（表格化）', '知识点—节点映射表'],
    apis: ['/kg/query', '/kg/detail/{dsu_id}', '/kg/stats'],
    subjects: ['中医智能', '知识图谱'], abilities: ['图谱查询', '双向遍历'],
    scenarios: ['应用开发', '数据核查'], stages: ['本科', '硕士'], standaloneSupport: 'needs_platform',
    tags: ['知识图谱', 'DSU', '以病索证', '以证溯病'],
  },
  {
    slug: 'tcm-icd11-coding', title: 'ICD-11 编码桥接 Skill', category: 'tcm-intelligence',
    summary: '把中医病证名称映射到 ICD-11（含传统医学章节）标准编码，走内网镜像零外网依赖。',
    problem: '中医病名与国际疾病分类之间存在多对多映射，人工查编码既慢又易错。本 Skill 固化三 header 调用规范与滑动窗口搜索策略。',
    bestFor: ['中医病案首页编码', '科研数据的国际标准对齐', '病证与 ICD-11 映射体系建设'],
    notFor: ['替代病案编码员的最终审核', '对镜像缺失的线性化端点做臆测'],
    inputs: ['中医病名 / 证型名称', '目标语言（zh / en）', '是否需要记录 ID 与编码双输出'],
    workflow: ['长词先做滑动窗口切分再检索', '按 API-Version / Accept / Accept-Language 三 header 调用', '命中后取实体 ID（如 BA00 / SF57）与标准编码', '对多候选做人工可判断的排序', '输出映射表并标注置信度'],
    outputs: ['病证—ICD-11 映射表', '实体 ID 与标准编码', '置信度与待确认项'],
    apis: ['/icd/*'],
    textbookCodes: ['CM-02', 'CM-13'], subjects: ['中医智能', '病案信息'], abilities: ['标准编码', '术语映射'],
    scenarios: ['科研对齐', '病案编码'], stages: ['本科', '硕士'], standaloneSupport: 'needs_platform',
    tags: ['ICD-11', '编码', '术语映射', '内网镜像'],
  },
  {
    slug: 'tcm-soul-agent-forge', title: '六者 SOUL 智能体锻造 Skill', category: 'tcm-intelligence',
    summary: '按六段式 SOUL 规范锻造角色人格，并注册到平台 /agents 端点完成上线。',
    problem: '角色智能体若无统一 SOUL 规范，会退化成换皮 prompt。本 Skill 固化六段式结构与注册流程，保证人格、知识边界、工具集三者一致。',
    bestFor: ['六者角色的新增与迭代', '医圣人格（张仲景 / 孙思邈）的扩展', '平台 Agent 注册与联调'],
    notFor: ['替代平台侧的安全与权限设计', '在无审核时直接上线生产人格'],
    inputs: ['角色（healer / patient / pharmacist / device / regulator / legal）', '人格来源（历史医圣 / 岗位角色）', '知识边界与工具集清单'],
    workflow: ['按六段式撰写 SOUL.md（身份 / 记忆 / 使命 / 规则 / 工具 / 边界）', '声明知识边界（可回答 / 必须转介）', '绑定工具集与平台 API', '本地一致性自检（自称、口吻、禁用词）', '走 /agents 三端点注册并做连通性验证'],
    outputs: ['SOUL.md', '知识边界与工具绑定表', '注册与连通性验证结果'],
    apis: ['/sages', '/agents/*'],
    subjects: ['中医智能', 'Agent 工程'], abilities: ['人格设计', '智能体注册'],
    scenarios: ['应用开发', '平台扩展'], stages: ['本科', '硕士', '继续教育'], standaloneSupport: 'needs_platform',
    tags: ['SOUL', '六者', '智能体', '人格'],
  },
  {
    slug: 'tcm-ai-course-lab', title: '中医 AI 课程实验 Skill', category: 'tcm-intelligence',
    summary: 'D07 中医智能学院的六阶实验线：TF-IDF 检索→倒排索引 RRF→RAG 对话→结构化输出→Agent SOUL→医院编排。',
    problem: '中医智能方向缺一条「从零到平台」的可跑实验线，学习者常在概念与工程之间断层。本 Skill 把 ai-curriculum 六阶实验串成可逐阶验收的课程。',
    bestFor: ['中医智能学院本科至研究生的实验课', '跨专业转入 AI 工程的补课', '平台二次开发者的上手路径'],
    notFor: ['替代机器学习与编程基础课', '跳过前置阶直接做医院编排'],
    inputs: ['当前所处的阶（01–06）', '编程基础水平', '实验环境（本地 Python / 平台）'],
    workflow: ['确认前置阶是否已通过验收', '给出本阶的目标、数据集与验收标准', '提供可运行代码骨架与测试', '跑通并核对输出', '记录到课程进度并进入下一阶'],
    outputs: ['单阶实验代码与测试', '验收结果', '课程进度记录'],
    subjects: ['中医智能', '软件工程'], abilities: ['工程实践', '检索与 RAG'],
    scenarios: ['课程实验', '自学路径'], stages: ['本科', '硕士', '继续教育'], standaloneSupport: 'needs_user_input',
    tags: ['AI课程', 'TF-IDF', 'RAG', 'Agent编排', 'D07'],
  },

  // ════════ tcm-management：中医管理 ════════
  {
    slug: 'tcm-quality-control', title: '中医医疗质控 Skill', category: 'tcm-management',
    summary: '把中医病历质量、辨证规范性与优势病种管理转成可抽查、可量化的质控指标。',
    problem: '中医质控难点在于「辨证」难以标准化评分。本 Skill 把辨证要素完整性、治法方药一致性拆成可抽查的评分项。',
    bestFor: ['中医医院质控科日常抽查', '中医病案质量评价培训', '科室质控指标体系建设'],
    notFor: ['替代卫生行政部门的法定检查', '对具体医疗纠纷做责任认定'],
    inputs: ['科室与抽查周期', '病历样本或质控维度选择', '现行质控指标（可选）'],
    workflow: ['确定质控维度（病历书写 / 辨证规范 / 用药合理 / 优势病种）', '按维度生成抽查清单', '给出可量化的评分规则', '调用 /regulators/quality 生成评估', '输出问题清单与改进建议'],
    outputs: ['质控抽查清单与评分规则', '问题清单', '改进建议'],
    apis: ['/regulators/quality', '/regulators/utilization', '/regulators/dashboard'],
    subjects: ['中医医院管理'], abilities: ['质控指标', '病历评价'],
    scenarios: ['医院管理', '继续教育'], stages: ['继续教育', '本科'], roles: ['regulator'], tags: ['质控', '病历', '优势病种'],
  },
  {
    slug: 'tcm-medical-insurance', title: '中医医保与法规 Skill', category: 'tcm-management',
    summary: '查清医保报销口径、药品分类与费用估算，并给出可复核的法规依据。',
    problem: '医保政策地域性强、更新频繁，且中医项目分类特殊。本 Skill 固化「先查法规、再算口径、最后留痕」的流程。',
    bestFor: ['医院医保办日常咨询', '临床科室费用沟通', '法者角色医保知识支持'],
    notFor: ['替代医保部门的正式答复', '对具体患者做出报销承诺'],
    inputs: ['医保类型（职工 / 居民 / 新农合）', '诊疗项目或药品名称', '就诊类型（门诊 / 住院）'],
    workflow: ['确定适用医保类型与政策版本', '调用 /legals/insurance/drug 查药品分类（A/B/C 类）', '调用 /legals/insurance/coverage 核报销口径', '调用 /legals/insurance/estimate 做费用估算', '输出结论 + 依据条款 + 待确认提示'],
    outputs: ['报销口径结论', '药品分类与自付比例', '费用估算与依据条款'],
    apis: ['/legals/insurance/coverage', '/legals/insurance/drug', '/legals/insurance/estimate', '/legals/regulation'],
    subjects: ['中医医院管理', '医事法学'], abilities: ['医保口径', '法规查询'],
    scenarios: ['医院管理', '患者沟通'], stages: ['继续教育'], roles: ['legal', 'regulator'], tags: ['医保', '药品分类', '费用估算', '法规'],
  },

  // ════════ tcm-learning-core：学习核心 ════════
  {
    slug: 'tcm-study-plan', title: '中医学习计划 Skill', category: 'tcm-learning-core',
    summary: '把模糊目标拆成今天、本周与下一轮可执行的中医学习安排。',
    problem: '中医学习周期长、门类多，目标一模糊就会陷入「今天看点啥都行」。本 Skill 用前置链与轮次编排给出确定性的每日任务。',
    bestFor: ['在校生的课程同步规划', '考研 / 执业医师的长周期备考规划', '师承人员的自主学习安排'],
    notFor: ['代替学校正式课程表', '在无目标、无时间、无水平信息时的空泛规划'],
    inputs: ['学习目标（同步 / 备考 / 师承）', '当前学段与基础', '每天可用时间', '截止日期与薄弱点'],
    workflow: ['澄清目标与时间约束', '按前置依赖排出学习顺序（中基→诊断→中药→方剂→内科）', '拆成本周与今日任务', '为每天任务设定可验收的产出', '预留复习与机动时间'],
    outputs: ['学习路径图（含前置链）', '周任务表与今日任务', '每日验收标准'],
    subjects: ['学习能力'], abilities: ['学习计划', '目标管理'],
    scenarios: ['今日学习', '考前规划', '师承安排'], stages: ['本科', '硕士', '规培', '继续教育'],
    tags: ['学习计划', '前置链', '核心链'],
  },
  {
    slug: 'tcm-mistake-review', title: '中医错题复盘 Skill', category: 'tcm-learning-core',
    summary: '把错题按「概念型 / 记忆型 / 推理型 / 粗心型」四类归因，并生成复测。',
    problem: '中医错题常被笼统归为「没背熟」，但真正的失分点是辨证推理错误。本 Skill 强制四类归因，让复习打在最痛处。',
    bestFor: ['执业医师与考研的题海复盘', '课程测验后的订正', '规培考核后的查漏'],
    notFor: ['替代教师对争议题目的裁定', '在无原题的纯记忆复述'],
    inputs: ['原题与你的作答', '正确答案与解析', '错误发生的时间与场景'],
    workflow: ['还原题目考点与所属学科', '做四类归因并给出判据', '提炼该考点的最小知识块', '生成 3 道同考点变式题', '排定 1 天 / 3 天 / 7 天复测'],
    outputs: ['错题归因卡', '最小知识块', '变式题与复测计划'],
    subjects: ['学习能力'], abilities: ['错题订正', '复习计划'],
    scenarios: ['错题订正', '单元复习'], stages: ['本科', '硕士', '规培'],
    tags: ['错题', '归因', '复测'],
  },
  {
    slug: 'tcm-photo-question', title: '中医拍照答疑 Skill', category: 'tcm-learning-core',
    summary: '上传舌象、方剂或教材截图，先识别可见信息再讲解，不臆测不可见内容。',
    problem: '拍照答疑最大的风险是「看了模糊的图就断言」，在中医舌诊场景尤其危险。本 Skill 强制先声明可辨识信息、再作答，并列出不可判定项。',
    bestFor: ['教材题目与方剂组成的现场答疑', '舌象照片的初步特征描述', '课后作业的逐题讲解'],
    notFor: ['对照片做诊断结论', '在图像不可辨识时强行作答'],
    inputs: ['图片（题目 / 舌象 / 方剂 / 教材页）', '希望得到的帮助（讲解 / 判分 / 特征描述）', '已知条件补充'],
    workflow: ['声明图片中可辨识与不可辨识的信息', '定位题型或场景（题目 / 舌象 / 方剂）', '给出分步讲解或特征描述', '标注不可判定项与需补充信息', '附一条同类变式题'],
    outputs: ['可辨识信息声明', '分步讲解', '不可判定项与变式题'],
    subjects: ['学习能力'], abilities: ['图像识题', '分步讲解'],
    scenarios: ['课后作业', '现场答疑'], stages: ['本科', '规培'],
    tags: ['拍照答疑', '舌象', '方剂识别'],
  },
  {
    slug: 'tcm-preview-review', title: '中医预习与每周复盘 Skill', category: 'tcm-learning-core',
    summary: '课前用问题清单预习，周末用「掌握了什么—还差什么」做结构化复盘。',
    problem: '中医课程节奏快，不预习听课效率低；不复盘则学一章丢一章。本 Skill 把预习与复盘固定成两个短流程。',
    bestFor: ['在校生按课表的同步预习', '每周一次的阶段复盘', '师承跟诊后的复盘'],
    notFor: ['替代课堂听讲与跟诊实践', '在没有课程信息时的空泛预习'],
    inputs: ['下次课的章节或主题', '本周学习内容清单', '自评掌握程度'],
    workflow: ['预习：生成 5 个带答案锚点的问题清单', '预习：标注预计难点', '复盘：按主题逐项自评掌握度', '复盘：找出「以为会其实不会」的项', '生成下周的优先级调整建议'],
    outputs: ['预习问题清单', '每周复盘表', '下周优先级建议'],
    subjects: ['学习能力'], abilities: ['预习', '阶段复盘'],
    scenarios: ['课前预习', '学习报告'], stages: ['本科', '硕士', '规培'],
    tags: ['预习', '周复盘', '掌握度自评'],
  },
  {
    slug: 'tcm-learning-report', title: '中医学情报告 Skill', category: 'tcm-learning-core',
    summary: '把学习行为与考核结果汇总成带证据的学情报告，供学生、教师、师承导师共用。',
    problem: '学情报告常停留在「态度端正、继续努力」。本 Skill 要求每条结论都带证据，并区分「已掌握 / 需巩固 / 未覆盖」。',
    bestFor: ['阶段考核后的学情分析', '师承导师了解学员进度', '教师做班级整体诊断'],
    notFor: ['替代正式考试成绩认定', '在无学习数据时生成结论'],
    inputs: ['统计周期', '学习行为记录（时长 / 完成率）', '考核成绩与错题分布', '受众（学生 / 教师 / 师承导师）'],
    workflow: ['汇总行为与成绩数据', '按学科主题算出掌握度分布', '区分已掌握 / 需巩固 / 未覆盖三档', '每条结论附数据证据', '给出下一周期的三条具体行动'],
    outputs: ['学情报告（分受众版本）', '掌握度分布表', '下一周期行动建议'],
    subjects: ['学习能力'], abilities: ['学情分析', '数据证据'],
    scenarios: ['学习报告', '家长沟通', '师承评估'], stages: ['本科', '硕士', '规培', '继续教育'],
    tags: ['学情', '掌握度', '师承评估'],
  },

  // ════════ tcm-exam-prep：考试备考 ════════
  {
    slug: 'tcm-licensed-physician-exam', title: '中医执业医师考试 Skill', category: 'tcm-exam-prep',
    summary: '按实践技能与医学综合两阶段拆解考纲，做诊断、提分优先级与限时训练闭环。',
    problem: '执业医师考试范围极广，考生常在没有诊断的情况下盲目刷题。本 Skill 先做分数诊断，再定提分优先级。',
    bestFor: ['中医执业医师（含助理）备考', '实践技能三站式的专项训练', '毕业后首次参加考试者'],
    notFor: ['替代官方考试大纲与报考政策', '对考试结果做任何承诺'],
    inputs: ['考试阶段（实践技能 / 综合笔试）与日期', '当前正确率或模考分数', '薄弱模块或最近错题', '每天可用时间'],
    workflow: ['按考纲做模块分数诊断', '排定提分优先级（性价比排序）', '生成限时训练与整卷模拟', '错题复盘并回填薄弱模块', '排定下次复测时间'],
    outputs: ['模块诊断表', '提分优先级清单', '限时训练与复测计划'],
    subjects: ['中医综合'], abilities: ['诊断提分', '限时训练'],
    scenarios: ['考前冲刺', '专项训练'], stages: ['本科', '继续教育'],
    tags: ['执业医师', '实践技能', '综合笔试', '提分优先级'],
  },
  {
    slug: 'tcm-postgraduate-exam', title: '考研中医综合 Skill', category: 'tcm-exam-prep',
    summary: '面向考研中医综合（中基 / 中诊 / 中药 / 方剂 / 内科 / 针灸），做长周期分段备考。',
    problem: '考研中医综合六门课互相牵连，且专业课与公共课抢时间。本 Skill 用前置链分段排期，避免「后期发现基础没打牢」。',
    bestFor: ['考研中医综合（学硕 / 专硕）全程备考', '在校生的两年长周期规划', '二战考生的薄弱环节补偿'],
    notFor: ['替代目标院校的招生简章与命题范围', '对录取结果做任何承诺'],
    inputs: ['目标院校与专业方向', '考试日期', '六门课当前水平自评', '每日可用时间（含公共课分配）'],
    workflow: ['按前置链排出六门课的先后次序', '划分基础 / 强化 / 冲刺三段并配比时间', '按段生成周任务与验收标准', '每段结束做一次全科模考', '根据模考结果动态调整下一段优先级'],
    outputs: ['六门课分段排期表', '每周任务与验收标准', '模考结果与动态调整建议'],
    subjects: ['中医综合'], abilities: ['长周期规划', '全科模考'],
    scenarios: ['考前规划', '寒暑假提升'], stages: ['本科'],
    tags: ['考研', '中医综合', '分段备考'],
  },
  {
    slug: 'tcm-residency-training', title: '住院医师规范化培训 Skill', category: 'tcm-exam-prep',
    summary: '按轮转科室与出科考核组织规培学习，对接医圣成长的病证数门槛。',
    problem: '规培的关键不是考试而是「病证覆盖量」与出科能力。本 Skill 把轮转计划与病证数门槛绑定，让进度可见。',
    bestFor: ['中医住院医师规范化培训学员', '轮转出科考核准备', '带教老师管理学员进度'],
    notFor: ['替代基地的正式考核结论', '在无轮转计划时的空泛安排'],
    inputs: ['当前轮转科室与起止时间', '本科室应掌握的病证清单', '已覆盖病证数量', '出科考核形式'],
    workflow: ['对齐轮转科室与出科要求', '拆出本科室必须覆盖的病证清单', '按周排定门诊 / 病房 / 查房学习任务', '统计病证覆盖数与缺口', '出科前做一次模拟考核'],
    outputs: ['轮转周计划', '病证覆盖统计与缺口', '出科模拟考核'],
    apis: ['/kg/query', '/kg/stats'],
    subjects: ['中医综合'], abilities: ['轮转管理', '病证覆盖'],
    scenarios: ['规培演练', '出科考核'], stages: ['规培'], roles: ['healer'],
    tags: ['规培', '轮转', '出科', '病证数'],
  },

  // ════════ tcm-role-agents：六者角色 ════════
  {
    slug: 'role-healer', title: '医者 Agent Skill（含师带徒）', category: 'tcm-role-agents',
    summary: '医者临床辅助与带教一体：病证推理、方剂推荐、师带徒教学与医圣成长路径规划。',
    problem: '医者是六者的核心枢纽，既要服务临床又要带教。若两者割裂，带教就会退化成脱离病例的讲授。本 Skill 强制「以病例为教学载体」。',
    bestFor: ['临床医师的辨证论治辅助', '年长医师带教年轻医生', '医圣成长路径的进度规划'],
    notFor: ['替代医师本人的临床决策与签字', '对急危重症给出门诊式处理'],
    inputs: ['主诉与四诊信息', '患者既往史与用药', '当前职称 / 成长阶段', '（带教场景）学员层级与学习目标'],
    workflow: ['调用 /consult/{sage_id} 取医圣辨证建议', '调用 /kg/query 核对病证单位依据', '输出治法方药并标注证据来源', '（带教）把病例改造成教学问题链并布置作业', '更新病证覆盖数与成长进度'],
    outputs: ['辨证论治建议与依据', '带教问题链与作业', '成长进度更新'],
    apis: ['/consult/{sage_id}', '/teach/{sage_id}', '/analyze-case/{sage_id}', '/kg/query', '/diag', '/bianzheng'],
    subjects: ['中医临床综合'], abilities: ['辨证论治', '师带徒教学'],
    scenarios: ['临床辅助', '师带徒', '成长评估'], stages: ['规培', '继续教育'],
    roles: ['healer'], levelGate: '住院医-1 起，随病证覆盖数解锁', standaloneSupport: 'needs_platform',
    tags: ['医者', '师带徒', '六者', '医圣成长'],
  },
  {
    slug: 'role-patient', title: '患者 Agent Skill', category: 'tcm-role-agents',
    summary: '面向患者的症状自查、导诊建议与用药说明，明确边界、突出就医提示。',
    problem: '患者端最大的风险是把辅助信息误当诊断。本 Skill 在所有输出中强制携带边界声明与就医提示，且不输出处方剂量。',
    bestFor: ['就诊前的症状梳理与导诊', '用药说明的白话解释', '康复期调护指导'],
    notFor: ['给出诊断结论或处方', '替代急诊判断'],
    inputs: ['主诉与症状（部位 / 性质 / 时长）', '年龄与基础疾病', '正在使用的药物'],
    workflow: ['调用 /patients/symptom-check 做症状梳理', '调用 /patients/triage 给导诊建议', '调用 /patients/medication 白话解释用药', '标注红旗症状与就医紧急度', '输出边界声明（不构成诊断）'],
    outputs: ['症状梳理表', '导诊建议与就医紧急度', '用药白话说明与边界声明'],
    apis: ['/patients/symptom-check', '/patients/triage', '/patients/medication'],
    subjects: ['健康科普'], abilities: ['症状自查', '导诊'],
    scenarios: ['就诊前准备', '康复调护'], stages: ['继续教育'],
    roles: ['patient'], standaloneSupport: 'needs_platform',
    tags: ['患者', '自查', '导诊', '就医提示'],
  },
  {
    slug: 'role-pharmacist', title: '药者 Agent Skill', category: 'tcm-role-agents',
    summary: '处方审核、相互作用核查、替代建议与饮片溯源一体化的药事服务能力。',
    problem: '中药处方审核需要同时看配伍禁忌、剂量与饮片质量，人工易漏。本 Skill 把四项核查固化成必过清单。',
    bestFor: ['中药房处方审核', '药物相互作用与妊娠禁忌核查', '饮片质量与溯源核查'],
    notFor: ['替代药师签字与法定审核责任', '在缺处方信息时给出发药结论'],
    inputs: ['处方内容（药味与剂量）', '患者信息（年龄 / 妊娠 / 基础病）', '待核查类型'],
    workflow: ['调用 /pharmacists/review 做处方审核', '调用 /pharmacists/interaction 核查相互作用与十八反十九畏', '调用 /pharmacists/substitute 给替代建议', '调用 /pharmacists/trace 核查饮片溯源与库存', '输出审核结论与拦截项'],
    outputs: ['处方审核结论', '相互作用与禁忌清单', '替代建议与溯源信息'],
    apis: ['/pharmacists/review', '/pharmacists/interaction', '/pharmacists/substitute', '/pharmacists/inventory', '/pharmacists/trace'],
    subjects: ['临床中药学', '药事管理'], abilities: ['处方审核', '饮片溯源'],
    scenarios: ['药事服务', '企业培训'], stages: ['本科', '继续教育'],
    roles: ['pharmacist'], standaloneSupport: 'needs_platform',
    tags: ['药者', '处方审核', '十八反', '溯源'],
  },
  {
    slug: 'role-device', title: '械者 Agent Skill', category: 'tcm-role-agents',
    summary: '中医诊疗设备的维护、影像辅助、采购论证与质控追溯，打通设备全生命周期。',
    problem: '中医医院的设备管理常与临床脱节，采购论证缺临床视角。本 Skill 把四个环节串成一条可追溯链。',
    bestFor: ['设备科日常维护与质控', '影像与诊疗设备的辅助判读', '设备采购论证材料准备'],
    notFor: ['替代设备厂商的维修资质与责任', '对影像做最终诊断结论'],
    inputs: ['设备名称与型号', '故障或需求描述', '科室与使用场景', '（采购）预算与临床需求'],
    workflow: ['调用 /devices/maintenance 生成维护方案', '调用 /devices/imaging 做影像辅助描述', '调用 /devices/procurement 生成采购论证', '调用 /devices/qc 输出质控指标', '调用 /devices/trace 记录全生命周期台账'],
    outputs: ['维护方案', '影像辅助描述（非诊断）', '采购论证与质控台账'],
    apis: ['/devices/maintenance', '/devices/imaging', '/devices/procurement', '/devices/qc', '/devices/trace', '/devices/emergency'],
    subjects: ['医疗设备管理'], abilities: ['设备维护', '采购论证'],
    scenarios: ['设备管理', '继续教育'], stages: ['继续教育'],
    roles: ['device'], standaloneSupport: 'needs_platform',
    tags: ['械者', '设备', '影像', '采购论证'],
  },
  {
    slug: 'role-regulator', title: '规者 Agent Skill', category: 'tcm-role-agents',
    summary: '质控管理、排班优化、资源利用与应急调度：用指标驱动医院运行。',
    problem: '医院运行管理依赖直觉排班与事后统计。本 Skill 用指标先行的方法，让调度决策先看数据再看经验。',
    bestFor: ['院办 / 质控 / 后勤的日常运行管理', '门诊与病房排班优化', '应急事件的分级调度'],
    notFor: ['替代院领导的最终管理决策', '对人事与薪酬做具体安排'],
    inputs: ['管理场景（质控 / 排班 / 利用 / 应急）', '当前指标数据', '约束条件（人力 / 场地 / 时段）'],
    workflow: ['调用 /regulators/quality 取质控指标', '调用 /regulators/utilization 看资源利用', '调用 /regulators/scheduling 生成排班方案', '对冲突场景调用 /regulators/dispatch 做分级调度', '汇总到 /regulators/dashboard 呈现'],
    outputs: ['质控指标与问题清单', '排班方案与利用率分析', '应急调度分级方案与驾驶舱数据'],
    apis: ['/regulators/quality', '/regulators/scheduling', '/regulators/utilization', '/regulators/dispatch', '/regulators/dashboard'],
    subjects: ['中医医院管理'], abilities: ['质控管理', '排班调度'],
    scenarios: ['医院管理', '继续教育'], stages: ['继续教育'],
    roles: ['regulator'], standaloneSupport: 'needs_platform',
    tags: ['规者', '质控', '排班', '应急调度'],
  },
  {
    slug: 'role-legal', title: '法者 Agent Skill', category: 'tcm-role-agents',
    summary: '医疗风险识别、知情同意、法规查询与纠纷预防，并覆盖医保报销合规口径。',
    problem: '医疗法务既要在事前预防又要能在事后取证，且中医项目法规依据分散。本 Skill 要求每条结论都定位到具体条款。',
    bestFor: ['医事法务与院办的风险防控', '知情同意文书规范性检查', '医保合规与纠纷预防培训'],
    notFor: ['替代执业律师的法律意见', '对具体案件做责任认定'],
    inputs: ['场景类型（风险 / 同意 / 法规 / 案例 / 预防 / 医保）', '事实描述与时间线', '涉及科室与人员', '关键词或条款线索'],
    workflow: ['调用 /legals/risk 做风险点识别与分级', '调用 /legals/consent 检查知情同意完整性', '调用 /legals/regulation 定位法规条款', '调用 /legals/cases 检索类案', '调用 /legals/prevention 输出预防措施清单'],
    outputs: ['风险分级清单', '知情同意检查结果', '法规条款依据与预防措施'],
    apis: ['/legals/risk', '/legals/consent', '/legals/regulation', '/legals/cases', '/legals/prevention'],
    subjects: ['医事法学'], abilities: ['风险防控', '法规查询'],
    scenarios: ['医院管理', '纠纷预防'], stages: ['继续教育'],
    roles: ['legal'], standaloneSupport: 'needs_platform',
    tags: ['法者', '风险', '知情同意', '纠纷预防'],
  },

  // ════════ tcm-sage-growth：医圣成长 ════════
  {
    slug: 'sage-mentorship', title: '医圣带教 Skill', category: 'tcm-sage-growth',
    summary: '调用张仲景 / 孙思邈人格做专题授课与病案点评，按学员层级调整深度。',
    problem: '医圣人格若只做问答，就浪费了其学术风格差异。本 Skill 用「人格—主题—层级」三维匹配，让张仲景讲六经、孙思邈讲博采众长。',
    bestFor: ['师带徒的专题教学', '病案的医圣视角点评', '不同学术流派的对比学习'],
    notFor: ['把医圣人格当作诊断权威', '脱离病例的纯风格模仿'],
    inputs: ['主题（如「少阳病辨治」）', '学员层级（住院医-1 / 主治医 / 副主任医）', '时长与侧重', '待点评病案（可选）'],
    workflow: ['按主题选择匹配的医圣人格', '调用 /teach/{sage_id} 生成分层讲解', '（有病案时）调用 /analyze-case/{sage_id} 做点评', '提炼可操作的临床要点', '布置一道可验证的作业'],
    outputs: ['分层讲解稿', '医圣视角病案点评', '临床要点与作业'],
    apis: ['/teach/{sage_id}', '/analyze-case/{sage_id}', '/sages', '/consult/{sage_id}'],
    subjects: ['中医各家学说'], abilities: ['师承教学', '流派对比'],
    scenarios: ['师带徒', '继续教育'], stages: ['规培', '继续教育'], roles: ['healer'],
    levelGate: '住院医-1 起', standaloneSupport: 'needs_platform',
    tags: ['医圣', '带教', '张仲景', '孙思邈', 'SOUL'],
  },
  {
    slug: 'sage-growth-path', title: '医圣成长路径 Skill', category: 'tcm-sage-growth',
    summary: '把职称阶段映射为病证数门槛与能力清单，给出可追踪、可考核的成长路径。',
    problem: '年轻医师常不清楚「到什么阶段该会什么」。本 Skill 把病证覆盖数、能力项与职称阶段绑定，让成长看得见。',
    bestFor: ['住院医至主治医的成长规划', '科室对青年医师的培养管理', '师承出师的能力评估'],
    notFor: ['替代医院人事与职称评审制度', '把病证数量当作能力的唯一标准'],
    inputs: ['当前职称 / 成长阶段', '已覆盖病证数与清单', '目标阶段与时间窗'],
    workflow: ['读取当前阶段的病证数门槛与能力清单', '比对已覆盖与缺口（调用 /kg/stats 与 /kg/query 统计）', '生成补齐缺口的月度计划', '设定阶段考核方式（模拟 / 病案 / 带教）', '更新成长进度并标记解锁的医圣人格'],
    outputs: ['成长阶段对照表（门槛 / 现状 / 缺口）', '月度补齐计划', '考核方式与进度更新'],
    apis: ['/kg/stats', '/kg/query', '/sages', '/teach/{sage_id}'],
    subjects: ['中医各家学说'], abilities: ['成长规划', '能力评估'],
    scenarios: ['成长评估', '师带徒'], stages: ['规培', '继续教育'], roles: ['healer'],
    levelGate: '住院医-1 → 学科带头人（六阶）', standaloneSupport: 'needs_platform',
    tags: ['医圣成长', '职称', '病证数', '梯度'],
  },

  // ════════ tcm-teacher-tools：教研工具 ════════
  {
    slug: 'tcm-lesson-prep', title: '中医备课 Skill', category: 'tcm-teacher-tools',
    summary: '按学时与学情生成教案：目标、重点难点、板书结构、课堂活动与作业。',
    problem: '中医课程概念密度大，备课容易变成「把教材抄成 PPT」。本 Skill 强制先定学习目标与难点，再设计课堂活动。',
    bestFor: ['中医药院校教师的日常备课', '师承带教者的专题课设计', '继续教育培训课程设计'],
    notFor: ['替代教学督导的正式评价', '在没有学时与学情信息时的通用教案'],
    inputs: ['课程与章节', '学时与学段', '学情（已学 / 未学 / 薄弱点）', '教学形式（讲授 / 讨论 / 实训）'],
    workflow: ['写清 3 条可测的学习目标', '标出重点与 2–3 个难点', '设计板书或概念结构图', '设计 2 个课堂活动或提问链', '配套作业与下节课预习提示'],
    outputs: ['教案（目标 / 重难点 / 结构图 / 活动）', '课堂提问链', '作业与预习提示'],
    subjects: ['教师发展'], abilities: ['教学设计', '重难点分析'],
    scenarios: ['备课', '教研'], stages: ['继续教育'],
    tags: ['备课', '教案', '重难点', '课堂活动'],
  },
  {
    slug: 'tcm-item-generation', title: '中医命题与组卷 Skill', category: 'tcm-teacher-tools',
    summary: '按知识点与难度分布命题组卷，自动配答案、解析、评分标准与双向细目表。',
    problem: '中医命题既要覆盖知识点又要控制难度分布，手工组卷极易偏斜。本 Skill 用双向细目表约束组卷。',
    bestFor: ['课程测验与期中期末组卷', '规培出科考核卷', '执业医师模拟卷组卷'],
    notFor: ['替代命题审核与保密管理', '生成超出大纲范围的题目'],
    inputs: ['考查范围（教材号 / 章节 / 病证清单）', '题型与题量', '难度分布（基础 / 提高 / 综合）', '是否需要双向细目表'],
    workflow: ['按考查范围列出知识点清单', '编制双向细目表（知识点 × 难度 × 题型）', '按分布生成题目', '为每题配答案、解析与评分标准', '自检覆盖率与难度分布是否达标'],
    outputs: ['试卷与答案', '逐题解析与评分标准', '双向细目表'],
    subjects: ['教师发展', '中医综合'], abilities: ['命题', '组卷'],
    scenarios: ['命题', '教研'], stages: ['继续教育'],
    tags: ['命题', '组卷', '双向细目表', '评分标准'],
  },
];
